### ISSUE TITLE
Error: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by dotpixel** [Viir/bots#4] opened 2020-01-17 23:29 UTC
Using:
2020-01-17.botengine.console
and
https://github.com/Viir/bots/tree/master/implement/applications/eve-online/eve-online-warp-to-0-autopilot
![2020-01-18_02-23-26](https://user-images.githubusercontent.com/13214678/72653080-662a0c80-399a-11ea-9f5f-6fd3d65a60dd.png)

**Comment by Viir** [comment] 2020-01-19 10:22
Thank you for the report!
Let's investigate this problem. I made this adapted version of the bot to give us more information about the cause: [https://github.com/Viir/bots/tree/b38dc47abda07c2fd0d87466ba09723c6c7ec2b8/implement/applications/eve-online/eve-online-warp-to-0-autopilot](https://github.com/Viir/bots/tree/b38dc47abda07c2fd0d87466ba09723c6c7ec2b8/implement/applications/eve-online/eve-online-warp-to-0-autopilot)

What text do you get in the console when running that version?

**Comment by Praevalidus** [comment] 2020-01-20 05:36
I have the same issue.
When using https://github.com/Viir/bots/tree/b38dc47abda07c2fd0d87466ba09723c6c7ec2b8/implement/applications/eve-online/eve-online-warp-to-0-autopilot the console text is:
![Capture](https://user-images.githubusercontent.com/60086251/72701282-832d2e00-3b9a-11ea-9ef1-cdb0ef348b93.PNG)

**Comment by Viir** [comment] 2020-01-20 08:09
The screenshot shows an `OverflowException` out of `Enumerable.Sum` in [`ReadCommittedMemoryRegionsFromProcessId`](https://github.com/Arcitectus/Sanderling/blob/63dc3c46641a11475bfad941f01c572d3b62e5c9/implement/read-memory-64-bit/Program.cs#L357-L420).

I only find one invocation of `Sum` in [`ReadCommittedMemoryRegionsFromProcessId`](https://github.com/Arcitectus/Sanderling/blob/63dc3c46641a11475bfad941f01c572d3b62e5c9/implement/read-memory-64-bit/Program.cs#L357-L420)

It looks like this crash will happen if the size of the committed memory regions in the EVE Online client is larger than `Int32.MaxValue` when executing this method.
This crash happens if the EVE Online client uses more memory at the time the bot takes the first memory reading. The threshold should be about 2 gigabytes.

Anyway, the fix seems trivial, so that I will integrate it soon in a new version of the bot.

**Comment by Viir** [comment] 2020-01-20 10:09
Seems like Github misunderstood my commit message.

**Comment by Viir** [comment] 2020-01-20 10:19
I fixed the bug causing the problem we saw in the last screenshot.

You can load the new version from https://github.com/Viir/bots/tree/4a7e5d56f56bf5c2a58b3e73f9e2c3e4c036523c/implement/applications/eve-online/eve-online-warp-to-0-autopilot

How does this version work for you?

**Comment by Praevalidus** [comment] 2020-01-20 10:59
Yes. Error is now fixed. Thank you.

**Comment by Viir** [comment] 2020-01-28 12:13
The fixed versions of the example bots have been integrated into the guides in the meantime.

**Closed by Viir** 2020-01-28 12:13 UTC
